### ISSUE TITLE
Deploy to Android with capacitor

### ISSUE THREAD

**Issue by BenOnTrack** [FunMiles/Planetiler_MapLibre_Sveltekit#3]
Hi @FunMiles 

Have you ever tried to run your project on Android?
I'm currently looking at a solution using `capacitor`, and I can serve a static page but it looks like the mbtiles is not copied over during the build hence the server can't access the tiles.

I'd be really grateful if you could have a look, and I'd appreciate any feedback! 

I like the concept currently used versus tileserver but I'd need to make sure it's viable on platform such as Android or IOS. Sveltekit and capacitor makes it (normally) super easy :)

**Comment by FunMiles** [comment]
I have done many projects that run on Android (I had a game with 7 million downloads. I let it die). I do not know capacitor but my approach has been with PWA (Progressive Web Apps). I have a sample PWA on github, though I should update it or go with some Vite project that does something similar (in fact, I am soon going to try that approach in another project).
The idea is that you run the app from a server and you can then install in on computers/iOS devices/Android devices without any additional work.
Are you aware of that approach? 

I had a quick glance at `capacitor` and they also mention PWA (they say Native PWAs).

The issue for any map application is that the tile file can be very large. I am not sure you want to bundle it in the app. For example, planet.mbtiles for the whole world is over 80GB of data. The tile file is essentially a database queried via SQL statement and if you can set up a cloud database, that might be a good way to approach the issue. Or you can save each tile in a file and upload the resulting static files to a server to access them.

With a PWA, the service worker can store the tiles that have been accessed and the map can work offline. A good PWA setup should be able to download the minimal set of tiles for a reasonable offline work. You would then have to deal with the case when the user is offline and tries to access to a tile that has not been downloaded, e.g. by zooming too much.

What kind of app are you trying to build?

**Comment by BenOnTrack** [comment]
Hi,
First of all thanks a lot for your feedback - i didn't intend to open issues but that's the only way I've found to contact you, so really appreciate it.
You may tell I'm new in the business, but I'm learning fast and based on the new trend it sounds like sveltekit + capacitor is an easy approach - this blog shows you how to create a static app in 5 min (https://ionic.io/blog/cross-platform-sveltekit-capacitor-application-yes-its-possible). Then this one https://khromov.se/how-i-published-a-gratitude-journaling-app-for-ios-and-android-using-sveltekit-and-capacitor/ kind of confirm my choice, but it does not exactly do what I'm looking for (and obviously lack the source code).

I don't know if you've ever heard of Maps.Me, or their open-source counterpart named OrganicMaps but basically I'm trying to develop something similar with maplibre and mbtiles instead. In other words, I'm actually looking at a full offline solution - as of now I'm pushing a planet.mbtiles that actually only covers the country I live in and I'm not expecting the push the 80gb on the app (my mbtiles is around 400mb). So basically I'd like this database to be locally queried, exactly the same way you've built this repo - but on android.

Looking a bit more into it, I've found I may need to use this kind of adapter https://kit.svelte.dev/docs/adapter-node but not yet successful. In other words, any help to run your current project on an android (or ios) platform would be appreciated :)

**Comment by FunMiles** [comment]
I know organic maps. I've installed it on my Android phone.
Essentially, it sounds to me that you are coming from a similar point of view from the one that got me started on this project.
Here are my thoughts to help you through it:

- I don't think it is a good idea to bundle the tiles inside the app. For more than one reason. First it makes the app very large and that will take a while to download to install it (400MB on a cell network takes a bit of time 😅). Second, map data from openstreetmap does get updated from time to time. It is better to allow downloading the updated data, which is possibly limited to a number of tiles.
- As mentioned above, building your app as a PWA may help you achieve the offline behavior without having to touch the code published here.
- Alternatively, you could modify [the code that fetches the tile](https://github.com/FunMiles/Planetiler_MapLibre_Sveltekit/blob/2cab51b88d7811e8408eebddab10efc1cd12aebe/src/Components/MapLibre.svelte#L6-L19) and use [`dexie`](https://dexie.org/) to cache the data.
- I have run adapter node and run PWA from a server setup on my local computer. It does take a bit of learning and experimentation to bind together all the technologies, but it is not super difficult. I've served my apps from that before moving them to cloudflare and vercel. The biggest difficulty is obtaining a signed SSL, as that is required for a PWA to be installable.

PS: Do you use the sveltekit discord channel? That is a way to contact me if you want a more interactive way of asking me for help. My handle is `Fun Miles`

**Comment by BenOnTrack** [comment]
Thanks! I'll start digging into PWA in that case, and I'll have a look at discord !
The intent to push the tile within the app was only for the MVP, as I agreed that shouldn't be the final solution

Cheers!
